# name: "DQLabs DBT Impact Analysis"
# description: "Performs impact analysis on DBT model changes using DQLabs API"

# inputs:
#   api_client_id:
#     description: "API Client ID to authenticate with DQLabs"
#     required: true
#   api_client_secret:
#     description: "API Client Secret credentials for authentication"
#     required: true
#   changed_files_list:
#     description: "Comma-separated list of changed DBT model files"
#     required: true

# outputs:
#   impact_summary:
#     description: "Formatted summary of the downstream impacts"

# runs:
#   using: "node16"
#   main: "index.js"

name: "DQLabs Impact Analysis"
description: "Performs DBT model impact analysis via DQLabs API during PRs and posts the results as a PR comment"
author: "YourOrg"

inputs:
  api_client_id:
    description: "API Client ID to authenticate with DQLabs"
    required: true

  api_client_secret:
    description: "API Client Secret for authentication with DQLabs"
    required: true

  changed_files_list:
    description: "Comma-separated list of changed DBT model files"
    required: true

  github_token:
    description: "GitHub token to comment on the Pull Request"
    required: true

  dqlabs_base_url:
    description: "Base URL of the DQLabs API"
    required: true

  dqlabs_createlink_url:
    description: "URL to create links in DQLabs"
    required: true

outputs:
  impact_markdown:
    description: "Markdown summary of the impact analysis"


runs:
  using: "node16"
  main: "index.js"