version: 2

models:
  - name: stg_claims
    description: >
                 "The claims staging model provides a standardized view of raw insurance claim data.
                  It captures information related to individual policy claims, including policy number, claim date, claim amount, status, and customer details.
                  This model ensures consistency in column naming and applies basic transformations (such as data type casting, null handling, and deduplication) to prepare claim data for downstream analytics and reporting."
    columns:
      - name: CLAIM_ID
        description: "This attribute contains all consumer claim id's"
        tests:
          - not_null          # fails if CLAIM_ID is null
          - unique            # fails if CLAIM_ID duplicates

      - name: STATUS
        description: "Current processing status of the claim (e.g., Open, Closed, Pending)."
        tests:
          - not_null
          - accepted_values:  # fails if STATUS has other than OPEN/CLOSED
              values: ['OPEN', 'CLOSED']

      - name: CLAIM_TYPE
        description: "This attribute contains type of the claims"
        tests:
          - accepted_values:  # fails if CLAIM_TYPE outside ALLOWED types
              values: ['AUTO', 'HEALTH', 'LIFE']

      - name: CLAIM_DATE
        tests:
          - not_null

      - name: POLICY_NUMBER
        tests:
          - not_null
          - unique

      - name: CUSTOMER_ID
        tests:
          - relationships:    # fails if CUSTOMER_ID not present in stg_customers
              to: ref('stg_customers')
              field: CUSTOMER_ID

