version: 2

seeds:
  - name: bankdistrict
    description: "Reference table containing US cities, districts, divisions, and states."
    columns:
      - name: CITY
        description: "City name"
        tests:
          - not_null

      - name: DISTRICT_ID
        description: "District identifier"
        tests:
          - not_null
          - unique

      - name: STATE_ABBREV
        description: "Two-letter state abbreviation"
        tests:
          - not_null
