version: 2

models:
  - name: stg_retail_sales
    description: Clean staging model for retail sales data with no nulls or duplicates
    columns:
      - name: RECORD_ID
        description: Primary key for retail sales
        tests:
          - unique
          - not_null

      - name: "DATE"
        description: Date of the sale
        tests:
          - not_null

      - name: STORE_ID
        description: Store identifier
        tests:
          - not_null

      - name: PRODUCT_NAME
        description: Name of the product sold
        tests:
          - not_null

      - name: CATEGORY
        description: Product category
        tests:
          - not_null

      - name: QUANTITY
        description: Quantity sold
        tests:
          - not_null
        
      - name: UNIT_PRICE
        description: Price per unit
        tests:
          - not_null
         

      - name: TOTAL_AMOUNT
        description: Total amount of the sale
        tests:
          - not_null

      - name: CUSTOMER_ID
        description: Customer identifier
        tests:
          - not_null

      - name: SALES_REP
        description: Sales representative
        tests:
          - not_null

      - name: REGION
        description: Sales region
        tests:
          - not_null
