version: 2

sources:
  - name: dqlabs_qa_retail_sales
    description: "Source table for retail sales data"
    database: DQLABS_QA
    schema: STAGING
    tables:
      - name: retail_sales
        description: "Raw retail sales data"
        columns:
          - name: STORE_ID
            description: "Store ID where the sale occurred"
            tests:
              - not_null

          - name: PRODUCT_NAME
            description: "Name of the product sold"
            tests:
              - not_null

          - name: CATEGORY
            description: "Category of the product"
            tests:
              - not_null

          - name: CUSTOMER_ID
            description: "ID of the customer making the purchase"
            tests:
              - not_null

          - name: REGION
            description: "Sales region"
            tests:
              - not_null
