version: 2

models:
  - name: stg_retail_sales
    description: "Staging model for retail sales"
    columns:
      - name: RECORD_ID
        tests:
          - not_null
          - unique

      - name: PRODUCT_NAME
        description: "Name of the product sold"
        # Removed not_null test

      - name: CUSTOMER_ID
        description: "Customer identifier"
        # Removed not_null test

      - name: DATE
        description: "Date of the sale"
        # Removed not_null test

      - name: CATEGORY
        tests:
          - not_null

      - name: QUANTITY
        tests:
          - not_null

      - name: UNIT_PRICE
        # Removed not_null test

      - name: TOTAL_AMOUNT
        tests:
          - not_null

      - name: SALES_REP
        tests:
          - not_null

      - name: REGION
        tests:
          - not_null
