version: 2

models:
  - name: fct_electronics_sales
    description: "Fact table for electronics sales"
    columns:
      - name: RECORD_ID
        description: "Unique record identifier"
        tests:
          - not_null
          - unique
      - name: PRICE
        description: "Price of the product"
        tests:
          - not_null
          # - positive_values  # Skipping this test by commenting it out
      - name: CALCULATED_TOTAL
        description: "Total calculated value"
        tests:
          - not_null
          - positive_values  # This test will run

  - name: fct_macbook_air_sales
    description: "Fact table for Macbook Air sales"
    columns:
      - name: RECORD_ID
        description: "Unique record identifier"
        tests:
          - not_null
          - unique
      - name: PRICE_TIER
        description: "Price tier for Macbook Air"
        tests:
          - accepted_values:
              values: ['BUDGET_MODEL', 'STANDARD_MODEL', 'PREMIUM_MODEL']
          # - positive_values  # Skipping this test by commenting it out
      - name: ESTIMATED_COMMISSION
        description: "Estimated commission"
        tests:
          - not_null
          - positive_values  # This test will run
