version: 2

models:
  - name: stg_retail_sales
    description: "Staging model for cleaned retail sales data"
    columns:
      - name: RECORD_ID
        description: "Unique record identifier"
        tests:
          - unique
          - not_null

      - name: DATE
        description: "Date of the sale"
        tests:
          - not_null

      - name: STORE_ID
        description: "Store identifier"
        tests:
          - not_null

      - name: PRODUCT_NAME
        description: "Name of the product sold"
        tests:
          - not_null

      - name: CATEGORY
        description: "Product category"
        tests:
          - not_null

      - name: QUANTITY
        description: "Quantity sold"
        tests:
          - not_null

      - name: UNIT_PRICE
        description: "Price per unit"
        # Removed the undefined 'positive_values' test

      - name: TOTAL_AMOUNT
        description: "Total amount of the sale"
        tests:
          - not_null

      - name: CUSTOMER_ID
        description: "Customer identifier"
        tests:
          - not_null

      - name: SALES_REP
        description: "Sales representative"
        tests:
          - not_null

      - name: REGION
        description: "Sal
