version: 2

sources:
  - name: dqlabs_qa_retail_sales
    description: "Source table for retail sales data"
    database: DQLABS_QA
    schema: STAGING
    tables:
      - name: retail_sales
        description: "Raw retail sales data"
        columns:
          - name: SALE_DATE
            description: "Date of sale"
            tests:
              - not_null

          - name: STORE_ID
            description: "Store ID where the sale occurred"
            tests:
              - not_null

          - name: PRODUCT_NAME
            description: "Name of the product sold"
            tests:
              - not_null

          - name: CATEGORY
            description: "Category of the product"
            tests:
              - not_null

          - name: CUSTOMER_ID
            description: "ID of the customer making the purchase"
            tests:
              - not_null

          - name: CUSTOMER_NAME
            description: "Name of the customer"
            tests:
              - not_null

          - name: REGION
            description: "Sales region"
            tests:
              - not_null

          - name: TIMESTAMP
            description: "Timestamp of when the record was created"
            tests:
              - not_null

          # Removed the positive value tests for these fields
          - name: QUANTITY
            description: "Quantity of the product sold"
            tests:
              - not_null  # Only keeping not_null test for QUANTITY

          - name: UNIT_PRICE
            description: "Price per unit of the product"
            tests:
              - not_null  # Only keeping not_null test for UNIT_PRICE

          - name: TOTAL_AMOUNT
            description: "Total sale amount (Quantity * Unit Price)"
            tests:
              - not_null  # Only keeping not_null test for TOTAL_AMOUNT
