version: 2

sources:
  - name: dqlabs_qa
    description: DQLABS QA environment source tables
    database: DQLABS_QA
    schema: STAGING
    tables:
      - name: retail_sales
        description: Raw retail sales data from staging
        columns:
          - name: RECORD_ID
            description: Unique record identifier
          - name: "DATE"
            description: Date of the sale
          - name: STORE_ID
            description: Store identifier
          - name: PRODUCT_NAME
            description: Name of the product sold
          - name: CATEGORY
            description: Product category
          - name: QUANTITY
            description: Quantity sold
          - name: UNIT_PRICE
            description: Price per unit
          - name: TOTAL_AMOUNT
            description: Total amount of the sale
          - name: CUSTOMER_ID
            description: Customer identifier
          - name: SALES_REP
            description: Sales representative
          - name: REGION
            description: Sales region
