version: 2
models:
  - name: stg_orders
    columns:
      - name: ORDER_ID
        tests:
          - unique
          - not_null
  - name: stg_customer
    columns:
      - name: CUSTOMER_ID
        tests:
          - unique:
            severity: warn
          - not_null:
            severity: warn